### PR TITLE
add canvasSetAutoGrow, canvasScrollTop, canvasSetAutoResize

### PR DESCRIPTION
**Pull request by kukac7**

### CODE REVIEW

**Comment by angelxmoreno** [comment]
Please fix the Travis errors

**Comment by kukac7** [comment]
@angelxmoreno how?

**Comment by angelxmoreno** [comment]
looks like the issues might not be with your code but with the travis setup trying to run tests. Let's have some of the project owners take a look at it. @AlmogBaku ?

**Comment by kukac7** [comment]
@angelxmoreno yes, I also think that it is not my code looks wrong. :smiley:

**Comment by AlmogBaku** [comment]
Interesting! I'll try to investigate the travis errors ASAP

**Comment by kukac7** [comment]
@AlmogBaku any news? :dancers:

**Comment by AlmogBaku** [comment]
I tested it localy

**Comment by AlmogBaku** [comment]
@kukac7 when you'll have the time, i'd love to see some tests for this :)

**Pull request merged**
